### ISSUE TITLE
Fix `Zotero.Date.init()` on non-`Zotero.isFx` platforms

### ISSUE THREAD

**Issue by dstillman** [zotero/utilities#3]
`strToDate()` (along with other functions) calls `getMonths()`, which is limited to English months without `Zotero.Date.init()`, which depends on `dateFormats.json`, which maybe we need to move into this repo? This would be necessary for proper [locale-based date parsing](https://github.com/zotero/web-library/issues/449) in the web library, for example.

**Comment by adomasven** [comment]
Seems easy enough. The utilities code client would be responsible for loading and passing `dateFormats.json` to `Zotero.Date.init()` just like they are for the schema (see [README.md](https://github.com/zotero/utilities/blob/master/README.md)).
